import Head from 'next/head'
import ChatWindow from '../components/ChatWindow'
import Info from '../components/Info'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { useContext } from 'react';
import { AppContext, AuthContext } from '../context';
import { getCookie } from '../common/functions';


export default function Home() {
  const { infoVisitor, haveCookie } = useContext(AppContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        {Object.keys(infoVisitor).length > 0 || haveCookie ? (
          <ChatWindow />
        ) : (
          <Info />
        )}
      </main>
    </div>
  )
}
