import Head from 'next/head'
import ChatWindow from '../components/ChatWindow'
import Info from '../components/Info'
import styles from '../styles/Home.module.css'
import { useContext, useEffect } from 'react';
import { AppContext, AuthContext } from '../context';
import { useRouter } from 'next/router';
import { getCookie } from '../common/functions';
import { Spinner } from 'react-bootstrap';


export default function Home() {
  const { haveCookie } = useContext(AppContext);
  const { currentUser } = useContext(AuthContext);
  const router = useRouter();
  useEffect(() => {
    if (currentUser) {
      if (currentUser.type === 2) {
        router.push("/admin");
      } else {
        router.push(`/room/${getCookie("room_id")}`);
      }
    }
  }, [currentUser])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        {currentUser && Object.keys(currentUser)?.length > 0 || haveCookie ? (
          <Spinner animation="border" variant="info" />
        ) : (
          <Info />
        )}
      </main>
    </div>
  )
}
