import Head from 'next/head'
import ChatWindow from '../components/ChatWindow'
import Info from '../components/Info'
import styles from '../styles/Home.module.css'
import { useContext } from 'react';
import { AppContext, AuthContext } from '../context';


export default function Home() {
  const { haveCookie } = useContext(AppContext);
  const { currentUser } = useContext(AuthContext);
  console.log(currentUser)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        {currentUser && Object.keys(currentUser)?.length > 0 || haveCookie ? (
          <span>home</span>
        ) : (
          <Info />
        )}
      </main>
    </div>
  )
}
